server:
  port: 8081
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #consumer
    listener:
      simple:
      #全局配置：公平派遣消息-消费者无应答并发消费数，默认为循环派遣
        prefetch: 2
        retry:
          #开启消费者重试-考虑幂等处理
          enabled: true
          #重试间隔时间ms
          initial-interval: 3000
          #最大重试次数
          max-attempts: 2
        #采用手动回答
        acknowledge-mode: manual

mybatis:
  type-aliases-package: com.rabbitmq.model
  mapper-locations: classpath:mapper/*Mapper.xml
#log_level config
LOG_LEVEL: INFO


# RABBIT (RabbitProperties)
#spring.rabbitmq.addresses= # Comma-separated list of addresses to which the client should connect.
#spring.rabbitmq.cache.channel.checkout-timeout= # Number of milliseconds to wait to obtain a channel if the cache size has been reached.
#spring.rabbitmq.cache.channel.size= # Number of channels to retain in the cache.
#spring.rabbitmq.cache.connection.mode=CHANNEL # Connection factory cache mode.
#spring.rabbitmq.cache.connection.size= # Number of connections to cache.
#spring.rabbitmq.connection-timeout= # Connection timeout, in milliseconds; zero for infinite.
#spring.rabbitmq.dynamic=true # Create an AmqpAdmin bean.
#spring.rabbitmq.host=localhost # RabbitMQ host.
#spring.rabbitmq.listener.acknowledge-mode= # Acknowledge mode of container.
#spring.rabbitmq.listener.auto-startup=true # Start the container automatically on startup.
#spring.rabbitmq.listener.concurrency= # Minimum number of consumers.
#spring.rabbitmq.listener.default-requeue-rejected= # Whether or not to requeue delivery failures; default `true`.
#spring.rabbitmq.listener.max-concurrency= # Maximum number of consumers.
#spring.rabbitmq.listener.prefetch= # Number of messages to be handled in a single request. It should be greater than or equal to the transaction size (if used).
#spring.rabbitmq.listener.retry.enabled=false # Whether or not publishing retries are enabled.
#spring.rabbitmq.listener.retry.initial-interval=1000 # Interval between the first and second attempt to deliver a message.
#spring.rabbitmq.listener.retry.max-attempts=3 # Maximum number of attempts to deliver a message.
#spring.rabbitmq.listener.retry.max-interval=10000 # Maximum interval between attempts.
#spring.rabbitmq.listener.retry.multiplier=1.0 # A multiplier to apply to the previous delivery retry interval.
#spring.rabbitmq.listener.retry.stateless=true # Whether or not retry is stateless or stateful.
#spring.rabbitmq.listener.transaction-size= # Number of messages to be processed in a transaction. For best results it should be less than or equal to the prefetch count.
#spring.rabbitmq.password= # Login to authenticate against the broker.
#spring.rabbitmq.port=5672 # RabbitMQ port.
#spring.rabbitmq.publisher-confirms=false # Enable publisher confirms.
#spring.rabbitmq.publisher-returns=false # Enable publisher returns.
#spring.rabbitmq.requested-heartbeat= # Requested heartbeat timeout, in seconds; zero for none.
#spring.rabbitmq.ssl.enabled=false # Enable SSL support.
#spring.rabbitmq.ssl.key-store= # Path to the key store that holds the SSL certificate.
#spring.rabbitmq.ssl.key-store-password= # Password used to access the key store.
#spring.rabbitmq.ssl.trust-store= # Trust store that holds SSL certificates.
#spring.rabbitmq.ssl.trust-store-password= # Password used to access the trust store.
#spring.rabbitmq.ssl.algorithm= # SSL algorithm to use. By default configure by the rabbit client library.
#spring.rabbitmq.template.mandatory=false # Enable mandatory messages.
#spring.rabbitmq.template.receive-timeout=0 # Timeout for `receive()` methods.
#spring.rabbitmq.template.reply-timeout=5000 # Timeout for `sendAndReceive()` methods.
#spring.rabbitmq.template.retry.enabled=false # Set to true to enable retries in the `RabbitTemplate`.
#spring.rabbitmq.template.retry.initial-interval=1000 # Interval between the first and second attempt to publish a message.
#spring.rabbitmq.template.retry.max-attempts=3 # Maximum number of attempts to publish a message.
#spring.rabbitmq.template.retry.max-interval=10000 # Maximum number of attempts to publish a message.
#spring.rabbitmq.template.retry.multiplier=1.0 # A multiplier to apply to the previous publishing retry interval.
#spring.rabbitmq.username= # Login user to authenticate to the broker.
#spring.rabbitmq.virtual-host= # Virtual host to use when connecting to the broker.